#关闭Thymeleaf的缓存
spring:
  thymeleaf:
    cache: false

  #国际化配置文件的真实位置
  messages:
    basename: i18n.login

  #修改日期格式
  mvc:
    format:
      date: yyyy-MM-dd

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/web?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.lxf.springbootweb.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml